name: Try to create VM

on:
  schedule:
    # Minimum allow interval is 5 minutes.
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows to run script manually for testing.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # Automatically caches dependencies from: requirements.txt

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create config file
        run: |
          echo "$CONFIG_DATA" > config.json
        env:
          CONFIG_DATA: ${{ secrets.CONFIG_FILE_CONTENT }}

      - name: Run script
        run: python oracle-cloud-vm-creator.py

      - name: Send Email on Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[IMPORTANT][SUCCESS]: Periodic Job for ${{ github.repository }}"
          to: ${{ secrets.MAIL_RECIPIENT }}
          from: "GitHub Actions Bot <${{ secrets.MAIL_USERNAME }}>"
          body: |
            The Python script in ${{ github.repository }} ran successfully.
            
            Workflow: ${{ github.workflow }}
            Run ID: ${{ github.run_id }}
